#!/usr/bin/env bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    lately [TERM...]"
    echo "      Display count of recently completed tasks that contain TERM(s)."
    echo ""
    exit
}

TODOTXT_VERBOSE=0

YESTERDAY=`date --date=yesterday +%F`
TODAY=`date +%F`
WEEK=`date --date="-8 days" +%F`
PREV7START=`date --date="-15 days" +%F`
PREV7END=`date --date="-7 days" +%F`

REGEXP=' x [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}'

yesterday_count=0
today_count=0
yesterday_list=
today_list=
week_list=
fortnight_list=

while read line
do
    date=$(echo "$line" | grep -o -E "$REGEXP" | sed -e 's/^ x //')
    if [[ "$date" = "$TODAY" ]]; then
        today_count=$((today_count+1))
        today_list+="$line\n"
    elif [[ "$date" = "$YESTERDAY" ]]; then
        yesterday_list+="$line\n"
        yesterday_count=$((yesterday_count+1))
    fi
    if [[ "$date" > "$WEEK" && "$date" < "$TODAY" ]]; then
        week_list+="$line\n"
    fi
    if [[ "$date" > "$PREV7START" && "$date" < "$PREV7END" ]]; then
        fortnight_list+="$line\n"
    fi
done < <(_list "$DONE_FILE" "$@" | grep -E "$REGEXP")

echo "=====  Done lately  ====="
echo "$TODAY: $today_count (today)"
echo "$YESTERDAY: $yesterday_count (yesterday)"

showList()
{
    list="$1"
    name="$2"

    if [[ -n "$list" && "$list" != "\n" ]]; then
        echo -e "\n---  $name  ---"
        echo -ne "$list"
    fi
}

showList "$today_list" "   Today   "
showList "$yesterday_list" " Yesterday "
showList "$week_list" "Last 7 Days"
showList "$fortnight_list" "Previous 7 Days"
