#!/usr/bin/env bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    lately [TERM...]"
    echo "      Display count of recently completed tasks that contain TERM(s)."
    echo ""
    exit
}

TODOTXT_VERBOSE=0

YESTERDAY=`date --date=yesterday +%F`
TODAY=`date +%F`

REGEXP=' x [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}'

yesterday_count=0
today_count=0

while read line
do
    date=$(echo "$line" | grep -o -E "$REGEXP" | sed -e 's/^ x //')
    if [[ "$date" = "$TODAY" ]]; then
        today_count=$((today_count+1))
    elif [[ "$date" = "$YESTERDAY" ]]; then
        yesterday_count=$((yesterday_count+1))
    fi
done < <(_list "$DONE_FILE" "$@" | grep -E "$REGEXP")

echo "=====  Done lately  ====="
echo "$TODAY: $today_count (today)"
echo "$YESTERDAY: $yesterday_count (yesterday)"
