#!/usr/bin/env bash

while read line
do
    TOMORROW=`date -v+1d +%F`
    if [[ "$line" =~ [[:space:]]t:([0-9]{4}-[0-9]{2}-[0-9]{2})[[:space:]] ]]; then
        if [[ $TOMORROW > ${BASH_REMATCH[1]} ]]; then
            echo "$line"
        fi
    else
        echo "$line"
    fi
done < /dev/stdin
